FROM parity/parity:latest
USER root
# COPY chain.json /home/parity/.local/share/io.parity.ethereum/chain.json
# COPY config.toml /home/parity/.local/share/io.parity.ethereum/config.toml
# CMD ["--config","/home/parity/.local/share/io.parity.ethereum/config.toml"]
